### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by kakol20** [Apostolique/Agar.io-bot#568] opened 2016-04-15 19:38 UTC
Sometimes the screen would be filled with a colour and the graphics that this script adds. So far, I've seen blue and green cover the screen

**Comment by ErmiyaEskandary** [comment] 2016-04-15 19:59
Duplicate of phantom bug

**Comment by ErmiyaEskandary** [comment] 2016-04-15 20:00
Issue #452 - fix in progress

**Closed** 2016-04-15 20:01 UTC

**Comment by Drflash55** [comment] 2016-04-17 22:58
It's fixed as of right now.
