### ISSUE TITLE
Display danger via color

### ISSUE THREAD

**Issue by Nitrogen-Dioxide** [Apostolique/Agar.io-bot#202] opened 2015-07-11 17:18 UTC
Display blob danger/edibility via color
Red - it can split and eat you
Orange - it can eat you, but not if it splits
Yellow - Same size as you
Green - you can eat it, but not if you split
Purple - you can split and still eat it

**Comment by Apostolique** [comment] 2015-07-11 19:16
Yellow is useless, otherwise I'll get around to green and purple when I start working on the actual splitting.

**Comment by Gjum** [comment] 2015-08-20 21:01
Duplicate of #247

**Closed** 2015-08-21 04:03 UTC
