### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by fedepro** [Apostolique/Agar.io-bot#445] opened 2015-10-19 17:43 UTC
Not fuound

**Comment by Drflash55** [comment] 2015-10-19 18:42
Sorry, what?

I can't understand the problem here.

**Comment by Apostolique** [comment] 2015-10-19 19:58
Can't understand either.

**Comment by alfaconstrictor1** [comment] 2015-10-19 20:11
Yo apostolique

Havent found another way to contact u so here I go

If you're capable of making an exact or better replica of raga minions, not actually a server and where I canbuy stuff, I just need one script that multithreads and opens 30 bots, multithreaded nd it uses a proxy scraper or sumthing and if u can do this im willing to pay up to $100 for this if u r interested just leave a msg and ill leave my skypename/email

Thx

**Comment by Apostolique** [comment] 2015-10-19 20:39
You should contact https://github.com/KristophPOL

He should be able to help you with that.

@KristophPOL

**Comment by alfaconstrictor1** [comment] 2015-10-19 20:48
Already done that, I know what he is capable of and he already has a project going on, agarhelper I know, this guy is insane but I know that you can do the same or better, I'm really in need of this, but I understand ya if you don't have time though, but it is unfortunate that kris doesn't want to sell his stuff, nor he ever watches/answers his emails. Whatevz lol. So if you still don't want to do this it's fine, but remember I'm capable of paying $100-$200

**Comment by Apostolique** [comment] 2015-10-19 22:44
If you don't mind waiting an other week, I can do something for you. I am currently in my exam week.

**Comment by alfaconstrictor1** [comment] 2015-10-20 05:21
Sure mate, I'll wait for you. Good luck.

**Comment by KristophPOL** [comment] 2015-10-20 09:44
@Apostolique I'm sorry it took so long but the previous Saturday had my wedding. Now I can slowly get back into the project.

**Comment by alfaconstrictor1** [comment] 2015-10-20 11:53
@mention kristophpol so you're able to do it for me?

**Comment by alfaconstrictor1** [comment] 2015-10-20 11:54
@kristophpol sorry wrong mention

**Comment by alfaconstrictor1** [comment] 2015-10-20 15:56
@Kristophpol disregard my messages, I'll wait for Apostolique no matter what

**Comment by Drflash55** [comment] 2015-10-22 15:12
This could also be closed, because the problem is not very clear...
@Apostolique Decide what you want to do...

**Comment by alfaconstrictor1** [comment] 2015-10-22 15:36
Excuse me? I don't know what your problem is, but you're probaly just in need of attention. Want me to clap my hands? Here we go. So please stop pretending like you're a moderator and go ahead and focus you on your own 'issues' on your repo. Nm you don't have one so stop pretending like you're someone important but let me adress this for you: we don't need someone that says when an issue should be closed, he clearly stated he'd do it in a week so if we keep this open he can notify me when he's ready. Didn't want to be read but you just don't deserve better if you're trying to seek attention
Have a nice day

@DrFlash55

**Comment by henopied** [comment] 2015-10-22 15:41
@alfaconstrictor1 he is not talking about your project he is talking about the issue that you replied to because the issue this is on has pretty much died as we have not heard back from the original author.

**Comment by alfaconstrictor1** [comment] 2015-10-22 15:52
@henopied I am aware of that since I told him that apostolique would notify me in a week andI didn't have another way of contacting him yet so he could notify me using this issue, otherwise I'd have to open a new issue

**Comment by henopied** [comment] 2015-10-22 15:53
@alfaconstrictor1 you can reply to a closed issue

**Comment by alfaconstrictor1** [comment] 2015-10-22 15:56
@henopied didn't know that, I don't use github a lot but still I don't see the point in closing an issue but aight, if you really want to. And Henopied, do you have skype? I need to talk to you and it's urgent, kind of job? Add me and we'll talk, can't mention it here. Skypename is same as my github name

**Comment by henopied** [comment] 2015-10-22 16:27
@alfaconstrictor1 skype not found, sorry.

**Comment by alfaconstrictor1** [comment] 2015-10-22 16:31
sorry, look for 'gammaxdelta'

thanks mate @henopied

**Comment by alfaconstrictor1** [comment] 2015-10-26 21:10
@apostolique hope your exam week went well. have some free time now?

**Comment by Drflash55** [comment] 2015-10-27 11:36
Thought his exam week was last week.

**Comment by alfaconstrictor1** [comment] 2015-10-27 15:42
'I am currently in my exam week.'
@drflash55

**Comment by AmazingGamerBoy** [comment] 2015-11-17 05:41
Anyone willing to help me create an agario suicide/feeder bot with over 150 bots? This needs to be a local script. It would be fine to edit another script such as pulviscriptor's. Will pay a bit of money if you want (but just a bit). Add me on skype to talk about this: Agario-Lord
My GitHub Account: AmazingGamerBoy

**Comment by Drflash55** [comment] 2016-02-21 16:20
This issue has an unsolved problem, and the problem was never explained properly...
Closed.

**Closed by Drflash55** 2016-02-21 16:20 UTC
