### ISSUE TITLE
Merge timer

### ISSUE THREAD

**Issue by xXtheguy52Xx** [Apostolique/Agar.io-bot#371] opened 2015-09-01 12:43 UTC
I don't know jack squat about coding, but I'm about 50-50 on reading it and I was wondering if somebody would add in some code so you would know when your split cells were ready to merge back

**Comment by eric-m** [comment] 2015-09-01 22:10
I've put a rudimentary merge timer on mine.  Basically, in the launcher, I created a global splitTimer, and I start it up whenever I press space.  Then do a quick calc and display next to the current time at the bottom of the screen.  It's a hack, because it starts off counting down from 30 seconds when I first start the bot, but it serves my purposes.  :)  You can see my hack-job in my fork, if you're interested...

https://github.com/eric-m/Agar.io-bot/blob/master/launcher.user.js

I'm on the novice side of JavaScript expertise...

**Comment by eric-m** [comment] 2015-09-05 01:36
I have a better split detector now on my fork.  It detects anytime the player is split, whether that was via space or colliding with a virus.  The re-merge timer resets to zero when you're back to one cell, regardless of whether you were merged or the rest of you was eaten...

https://github.com/eric-m/Agar.io-bot

**Comment by ErmiyaEskandary** [comment] 2016-04-11 18:02
@eric-m Make a PR and I'll see if I can merge it.

**Comment by ErmiyaEskandary** [comment] 2016-04-16 09:32
Duplicate of #267

**Closed** 2016-04-16 09:33 UTC
Labels: Enhancement, SOON
