### ISSUE TITLE
Enhancement: Cell color-coating. 

### ISSUE THREAD

**Issue by Crayder** [Apostolique/Agar.io-bot#251] opened 2015-07-22 19:56 UTC
It would be nice to have color coated cells. This would be much like the old, [seemingly abandoned,] "Agar.io Extended" Chrome extenstion. I suggest using better colors though, that extension was very confusing.

**Comment by individuell** [comment] 2015-08-12 21:27
Is there currently an alternative to the Chrome extension you mentioned?
I am having a very hard time to estimate if the target cell is small enough for me to shoot at it.

Or is it possible to see it within the displayed lines?

**Comment by Gjum** [comment] 2015-08-20 21:01
Possible duplicate of #247

**Comment by Crayder** [comment] 2015-08-20 21:21
@Gjum this isn't stack exchange, duplicates are OK.

@individuell yes, the circles currently do show some things about enemies. If they don't have a circle, you can eat them; if they have a small circle, they can eat you without splitting; if they have a large circle, get the fuck away because they can split and eat you.

**Comment by individuell** [comment] 2015-08-20 21:28
@Crayder I'm gonna have to disagree on that part - currently, if they don't have a circle, they are just not dangerous to you. If they are the same size as you, they have no circle. So you can't tell if they are small enough for you to eat them or just over the limit. You have to be 10% bigger when you eat him, and 33% bigger when you split kill them iirc.

**Comment by Crayder** [comment] 2015-08-20 21:38
You are very correct, no circle, no danger.

**Comment by ErmiyaEskandary** [comment] 2016-04-12 11:47
Duplicate of #247.

**Closed by ErmiyaEskandary** 2016-04-12 11:47 UTC
