### ISSUE TITLE
I get this screen

### ISSUE THREAD

**Issue by RishabSwift** [Apostolique/Agar.io-bot#470] opened 2015-11-21 02:25 UTC
I keep getting this blue screen:

<img width="1440" alt="blue screen" src="https://cloud.githubusercontent.com/assets/15897093/11316126/1604e93a-8fcd-11e5-91e7-9952827e5ac9.png">

It keeps doing this and I don't know why. It does it on Firefox, chrome and opera all. I'm Using a mac.

**Comment by Apostolique** [comment] 2015-11-21 03:52
It's a bug in the current version. I'm almost done fixing it, but I had other projects that needed to be worked on first.

**Comment by RishabSwift** [comment] 2015-11-21 16:59
Oh okay, thanks. Any idea when it will be released?

**Comment by Apostolique** [comment] 2015-11-21 21:19
Hopefully today.

**Comment by RishabSwift** [comment] 2015-11-22 01:55
Awesome! I've been refreshing like crazy!

**Comment by Apostolique** [comment] 2015-11-22 03:14
I'm almost done, but I still have Javascript errors.

**Comment by PixieScr** [comment] 2015-11-22 03:51
I have this problem too and waiting for fix :)

**Comment by aryan4144** [comment] 2015-11-22 09:54
and some Chinese on the blue screen.l

**Comment by riccardosimo** [comment] 2015-11-22 17:29
LOL you're the best apossssssss <3

**Comment by rogerb831** [comment] 2015-11-22 20:45
I'm running into this on the feeder bot an the pop bot also. Maybe its related to the launcher if they are all suffering from it?

**Comment by rogerb831** [comment] 2015-11-22 21:59
I just confirmed that this problem is not happening with launcher ver 4.146

**Comment by Drflash55** [comment] 2015-11-24 11:42
A duplicate of #452.

**Comment by Drflash55** [comment] 2015-11-24 11:43
@Apostolique You plan on releasing it today?
Or are those JS errors holding you for longer than you expected?

**Comment by Apostolique** [comment] 2015-11-24 19:33
Oh..... I was still stuck on my Javascript errors, but your comment just gave me a massive idea. Turns out my problem is solved. Just need to finish putting it all together.

**Comment by malickf** [comment] 2015-12-03 05:34
I have the same problem

**Comment by muratlahur** [comment] 2015-12-14 09:44
No more blue screens, no more crashes, no more stuttering, no more ads . . . .

Little Smart Dot release date announced to be 20th Dec. can't wait 
it even comes with it's own fancy subdomain lol :P 

http://agar.strlbs.com

**Comment by Botlike420** [comment] 2015-12-20 14:48
Happy to found your bot but i also am running into the blue and greenscreenproblem. Also would it be possible to let the bot go after bots and smaller players?

**Comment by PFCKrutonium** [comment] 2015-12-26 13:02
Also still running into this error. :/

**Comment by Drflash55** [comment] 2016-02-21 16:13
Use #452 for discussions on this bug.

**Closed** 2016-02-21 16:12 UTC
