### ISSUE TITLE
Bot Freezes

### ISSUE THREAD

**Issue by Progamer213** [Apostolique/Agar.io-bot#167] opened 2015-06-28 17:10 UTC
Every time i eat a dot the bot freezes for 1 second and i end up getting eating by someone bigger than me it does this on the Aposbot and the Aposbotbeta please fix this or i wont use the bot anymore

**Comment by Apostolique** [comment] 2015-06-28 18:49
I can't reproduce the bug so I won't be able to help you unless you provide me with more details. Which browser you're using would be a good place to start. Does it still do that when you choose human mode?

**Comment by DarkN3ss61** [comment] 2015-06-28 21:21
Try disabling the a lines with "R" that may fix it. My initial thought is that it is the lag of the lines that is freezing the game

**Comment by Progamer213** [comment] 2015-06-29 18:40
Never mind i reinstalled the script and it worked fine again and by the way i was using google crome i guess the new update for the script installed wrong

**Comment by DarkN3ss61** [comment] 2015-06-30 07:03
@Apostolique Close this now

**Closed** 2015-06-30 07:03 UTC
